export const marinabay = [
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:50.417',
    milliseconds: 110417,
    year: 2014,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:51.280',
    milliseconds: 111280,
    year: 2014,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:51.405',
    milliseconds: 111405,
    year: 2014,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:51.465',
    milliseconds: 111465,
    year: 2014,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:51.474',
    milliseconds: 111474,
    year: 2014,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:50.041',
    milliseconds: 110041,
    year: 2015,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:50.069',
    milliseconds: 110069,
    year: 2015,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:50.075',
    milliseconds: 110075,
    year: 2015,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:50.118',
    milliseconds: 110118,
    year: 2015,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:50.174',
    milliseconds: 110174,
    year: 2015,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:47.187',
    milliseconds: 107187,
    year: 2016,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:47.345',
    milliseconds: 107345,
    year: 2016,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:47.630',
    milliseconds: 107630,
    year: 2016,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:47.706',
    milliseconds: 107706,
    year: 2016,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:47.752',
    milliseconds: 107752,
    year: 2016,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:45.008',
    milliseconds: 105008,
    year: 2017,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:45.301',
    milliseconds: 105301,
    year: 2017,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Valtteri',
    surname: 'Bottas',
    nationality: 'Finnish',
    time_x: '1:45.405',
    milliseconds: 105405,
    year: 2017,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:45.426',
    milliseconds: 105426,
    year: 2017,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:45.467',
    milliseconds: 105467,
    year: 2017,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Kevin',
    surname: 'Magnussen',
    nationality: 'Danish',
    time_x: '1:41.905',
    milliseconds: 101905,
    year: 2018,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:42.913',
    milliseconds: 102913,
    year: 2018,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:43.120',
    milliseconds: 103120,
    year: 2018,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Fernando',
    surname: 'Alonso',
    nationality: 'Spanish',
    time_x: '1:43.164',
    milliseconds: 103164,
    year: 2018,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:43.214',
    milliseconds: 103214,
    year: 2018,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Kevin',
    surname: 'Magnussen',
    nationality: 'Danish',
    time_x: '1:42.301',
    milliseconds: 102301,
    year: 2019,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Valtteri',
    surname: 'Bottas',
    nationality: 'Finnish',
    time_x: '1:43.534',
    milliseconds: 103534,
    year: 2019,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Kevin',
    surname: 'Magnussen',
    nationality: 'Danish',
    time_x: '1:43.828',
    milliseconds: 103828,
    year: 2019,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Daniil',
    surname: 'Kvyat',
    nationality: 'Russian',
    time_x: '1:44.371',
    milliseconds: 104371,
    year: 2019,
    name_y: 'Marina Bay Street Circuit',
  },
  {
    forename: 'Charles',
    surname: 'Leclerc',
    nationality: 'Monegasque',
    time_x: '1:44.723',
    milliseconds: 104723,
    year: 2019,
    name_y: 'Marina Bay Street Circuit',
  },
];
