const monaco = [
  {
    forename: 'Kimi',
    surname: 'R\u00e4ikk\u00f6nen',
    nationality: 'Finnish',
    time_x: '1:18.479',
    milliseconds: 78479,
    year: 2014,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Kimi',
    surname: 'R\u00e4ikk\u00f6nen',
    nationality: 'Finnish',
    time_x: '1:18.736',
    milliseconds: 78736,
    year: 2014,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:19.252',
    milliseconds: 79252,
    year: 2014,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:19.316',
    milliseconds: 79316,
    year: 2014,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:19.361',
    milliseconds: 79361,
    year: 2014,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:18.063',
    milliseconds: 78063,
    year: 2015,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:18.511',
    milliseconds: 78511,
    year: 2015,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:18.599',
    milliseconds: 78599,
    year: 2015,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:18.603',
    milliseconds: 78603,
    year: 2015,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:18.607',
    milliseconds: 78607,
    year: 2015,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:17.939',
    milliseconds: 77939,
    year: 2016,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:18.005',
    milliseconds: 78005,
    year: 2016,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:18.218',
    milliseconds: 78218,
    year: 2016,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:18.294',
    milliseconds: 78294,
    year: 2016,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:18.337',
    milliseconds: 78337,
    year: 2016,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Sergio',
    surname: 'P\u00e9rez',
    nationality: 'Mexican',
    time_x: '1:14.820',
    milliseconds: 74820,
    year: 2017,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Sergio',
    surname: 'P\u00e9rez',
    nationality: 'Mexican',
    time_x: '1:14.946',
    milliseconds: 74946,
    year: 2017,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Sergio',
    surname: 'P\u00e9rez',
    nationality: 'Mexican',
    time_x: '1:15.017',
    milliseconds: 75017,
    year: 2017,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:15.238',
    milliseconds: 75238,
    year: 2017,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Kimi',
    surname: 'R\u00e4ikk\u00f6nen',
    nationality: 'Finnish',
    time_x: '1:15.527',
    milliseconds: 75527,
    year: 2017,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Max',
    surname: 'Verstappen',
    nationality: 'Dutch',
    time_x: '1:14.260',
    milliseconds: 74260,
    year: 2018,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Max',
    surname: 'Verstappen',
    nationality: 'Dutch',
    time_x: '1:14.747',
    milliseconds: 74747,
    year: 2018,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Romain',
    surname: 'Grosjean',
    nationality: 'French',
    time_x: '1:14.822',
    milliseconds: 74822,
    year: 2018,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Max',
    surname: 'Verstappen',
    nationality: 'Dutch',
    time_x: '1:14.847',
    milliseconds: 74847,
    year: 2018,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Lance',
    surname: 'Stroll',
    nationality: 'Canadian',
    time_x: '1:14.944',
    milliseconds: 74944,
    year: 2018,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Pierre',
    surname: 'Gasly',
    nationality: 'French',
    time_x: '1:14.279',
    milliseconds: 74279,
    year: 2019,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Pierre',
    surname: 'Gasly',
    nationality: 'French',
    time_x: '1:14.301',
    milliseconds: 74301,
    year: 2019,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Pierre',
    surname: 'Gasly',
    nationality: 'French',
    time_x: '1:14.371',
    milliseconds: 74371,
    year: 2019,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Pierre',
    surname: 'Gasly',
    nationality: 'French',
    time_x: '1:14.567',
    milliseconds: 74567,
    year: 2019,
    name_y: 'Circuit de Monaco',
  },
  {
    forename: 'Pierre',
    surname: 'Gasly',
    nationality: 'French',
    time_x: '1:14.788',
    milliseconds: 74788,
    year: 2019,
    name_y: 'Circuit de Monaco',
  },
];

export { monaco };
