export const monza = [
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:28.004',
    milliseconds: 88004,
    year: 2014,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:28.053',
    milliseconds: 88053,
    year: 2014,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:28.088',
    milliseconds: 88088,
    year: 2014,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:28.206',
    milliseconds: 88206,
    year: 2014,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:28.320',
    milliseconds: 88320,
    year: 2014,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:26.672',
    milliseconds: 86672,
    year: 2015,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:26.890',
    milliseconds: 86890,
    year: 2015,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:26.985',
    milliseconds: 86985,
    year: 2015,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:27.036',
    milliseconds: 87036,
    year: 2015,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:27.050',
    milliseconds: 87050,
    year: 2015,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Fernando',
    surname: 'Alonso',
    nationality: 'Spanish',
    time_x: '1:25.340',
    milliseconds: 85340,
    year: 2016,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:25.919',
    milliseconds: 85919,
    year: 2016,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Kimi',
    surname: 'R\u00e4ikk\u00f6nen',
    nationality: 'Finnish',
    time_x: '1:26.016',
    milliseconds: 86016,
    year: 2016,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:26.252',
    milliseconds: 86252,
    year: 2016,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Kimi',
    surname: 'R\u00e4ikk\u00f6nen',
    nationality: 'Finnish',
    time_x: '1:26.268',
    milliseconds: 86268,
    year: 2016,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:23.361',
    milliseconds: 83361,
    year: 2017,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:23.488',
    milliseconds: 83488,
    year: 2017,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:23.542',
    milliseconds: 83542,
    year: 2017,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:23.675',
    milliseconds: 83675,
    year: 2017,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Valtteri',
    surname: 'Bottas',
    nationality: 'Finnish',
    time_x: '1:23.722',
    milliseconds: 83722,
    year: 2017,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:22.497',
    milliseconds: 82497,
    year: 2018,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:22.505',
    milliseconds: 82505,
    year: 2018,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:22.702',
    milliseconds: 82702,
    year: 2018,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:22.718',
    milliseconds: 82718,
    year: 2018,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:22.828',
    milliseconds: 82828,
    year: 2018,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:21.779',
    milliseconds: 81779,
    year: 2019,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:22.799',
    milliseconds: 82799,
    year: 2019,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Valtteri',
    surname: 'Bottas',
    nationality: 'Finnish',
    time_x: '1:22.859',
    milliseconds: 82859,
    year: 2019,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Valtteri',
    surname: 'Bottas',
    nationality: 'Finnish',
    time_x: '1:22.896',
    milliseconds: 82896,
    year: 2019,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:22.912',
    milliseconds: 82912,
    year: 2019,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:22.746',
    milliseconds: 82746,
    year: 2020,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:22.901',
    milliseconds: 82901,
    year: 2020,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:22.908',
    milliseconds: 82908,
    year: 2020,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:22.955',
    milliseconds: 82955,
    year: 2020,
    name_y: 'Autodromo Nazionale di Monza',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:23.334',
    milliseconds: 83334,
    year: 2020,
    name_y: 'Autodromo Nazionale di Monza',
  },
];
