export const redbull = [
  {
    forename: 'Sergio',
    surname: 'P\u00e9rez',
    nationality: 'Mexican',
    time_x: '1:12.142',
    milliseconds: 72142,
    year: 2014,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:12.217',
    milliseconds: 72217,
    year: 2014,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Sergio',
    surname: 'P\u00e9rez',
    nationality: 'Mexican',
    time_x: '1:12.257',
    milliseconds: 72257,
    year: 2014,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Sergio',
    surname: 'P\u00e9rez',
    nationality: 'Mexican',
    time_x: '1:12.299',
    milliseconds: 72299,
    year: 2014,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Sergio',
    surname: 'P\u00e9rez',
    nationality: 'Mexican',
    time_x: '1:12.374',
    milliseconds: 72374,
    year: 2014,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:11.235',
    milliseconds: 71235,
    year: 2015,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:11.445',
    milliseconds: 71445,
    year: 2015,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:11.475',
    milliseconds: 71475,
    year: 2015,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:11.499',
    milliseconds: 71499,
    year: 2015,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:11.514',
    milliseconds: 71514,
    year: 2015,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:08.411',
    milliseconds: 68411,
    year: 2016,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:08.442',
    milliseconds: 68442,
    year: 2016,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:08.491',
    milliseconds: 68491,
    year: 2016,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:08.524',
    milliseconds: 68524,
    year: 2016,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:08.598',
    milliseconds: 68598,
    year: 2016,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:07.411',
    milliseconds: 67411,
    year: 2017,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:07.424',
    milliseconds: 67424,
    year: 2017,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:07.442',
    milliseconds: 67442,
    year: 2017,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Kimi',
    surname: 'R\u00e4ikk\u00f6nen',
    nationality: 'Finnish',
    time_x: '1:07.486',
    milliseconds: 67486,
    year: 2017,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:07.496',
    milliseconds: 67496,
    year: 2017,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Kimi',
    surname: 'R\u00e4ikk\u00f6nen',
    nationality: 'Finnish',
    time_x: '1:06.957',
    milliseconds: 66957,
    year: 2018,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Kimi',
    surname: 'R\u00e4ikk\u00f6nen',
    nationality: 'Finnish',
    time_x: '1:06.975',
    milliseconds: 66975,
    year: 2018,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:07.082',
    milliseconds: 67082,
    year: 2018,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:07.180',
    milliseconds: 67180,
    year: 2018,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:07.183',
    milliseconds: 67183,
    year: 2018,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Max',
    surname: 'Verstappen',
    nationality: 'Dutch',
    time_x: '1:07.475',
    milliseconds: 67475,
    year: 2019,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Max',
    surname: 'Verstappen',
    nationality: 'Dutch',
    time_x: '1:07.592',
    milliseconds: 67592,
    year: 2019,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Max',
    surname: 'Verstappen',
    nationality: 'Dutch',
    time_x: '1:07.605',
    milliseconds: 67605,
    year: 2019,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:07.676',
    milliseconds: 67676,
    year: 2019,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Max',
    surname: 'Verstappen',
    nationality: 'Dutch',
    time_x: '1:07.750',
    milliseconds: 67750,
    year: 2019,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Carlos',
    surname: 'Sainz',
    nationality: 'Spanish',
    time_x: '1:05.619',
    milliseconds: 65619,
    year: 2020,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Max',
    surname: 'Verstappen',
    nationality: 'Dutch',
    time_x: '1:06.145',
    milliseconds: 66145,
    year: 2020,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Max',
    surname: 'Verstappen',
    nationality: 'Dutch',
    time_x: '1:06.599',
    milliseconds: 66599,
    year: 2020,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:06.719',
    milliseconds: 66719,
    year: 2020,
    name_y: 'Red Bull Ring',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:07.018',
    milliseconds: 67018,
    year: 2020,
    name_y: 'Red Bull Ring',
  },
];
