export const spa = [
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:50.511',
    milliseconds: 110511,
    year: 2014,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:50.856',
    milliseconds: 110856,
    year: 2014,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:50.905',
    milliseconds: 110905,
    year: 2014,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:51.104',
    milliseconds: 111104,
    year: 2014,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:51.168',
    milliseconds: 111168,
    year: 2014,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:52.416',
    milliseconds: 112416,
    year: 2015,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:52.504',
    milliseconds: 112504,
    year: 2015,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:52.511',
    milliseconds: 112511,
    year: 2015,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:52.559',
    milliseconds: 112559,
    year: 2015,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:52.669',
    milliseconds: 112669,
    year: 2015,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:51.583',
    milliseconds: 111583,
    year: 2016,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:51.692',
    milliseconds: 111692,
    year: 2016,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Nico',
    surname: 'Rosberg',
    nationality: 'German',
    time_x: '1:51.746',
    milliseconds: 111746,
    year: 2016,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:51.778',
    milliseconds: 111778,
    year: 2016,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:51.974',
    milliseconds: 111974,
    year: 2016,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:46.577',
    milliseconds: 106577,
    year: 2017,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:46.603',
    milliseconds: 106603,
    year: 2017,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:46.617',
    milliseconds: 106617,
    year: 2017,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:46.654',
    milliseconds: 106654,
    year: 2017,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:46.678',
    milliseconds: 106678,
    year: 2017,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Valtteri',
    surname: 'Bottas',
    nationality: 'Finnish',
    time_x: '1:46.286',
    milliseconds: 106286,
    year: 2018,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:46.644',
    milliseconds: 106644,
    year: 2018,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:46.721',
    milliseconds: 106721,
    year: 2018,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Valtteri',
    surname: 'Bottas',
    nationality: 'Finnish',
    time_x: '1:46.732',
    milliseconds: 106732,
    year: 2018,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:46.734',
    milliseconds: 106734,
    year: 2018,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:46.409',
    milliseconds: 106409,
    year: 2019,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Valtteri',
    surname: 'Bottas',
    nationality: 'Finnish',
    time_x: '1:46.465',
    milliseconds: 106465,
    year: 2019,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Valtteri',
    surname: 'Bottas',
    nationality: 'Finnish',
    time_x: '1:46.551',
    milliseconds: 106551,
    year: 2019,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Sebastian',
    surname: 'Vettel',
    nationality: 'German',
    time_x: '1:46.570',
    milliseconds: 106570,
    year: 2019,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:46.580',
    milliseconds: 106580,
    year: 2019,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Daniel',
    surname: 'Ricciardo',
    nationality: 'Australian',
    time_x: '1:47.483',
    milliseconds: 107483,
    year: 2020,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Lewis',
    surname: 'Hamilton',
    nationality: 'British',
    time_x: '1:47.758',
    milliseconds: 107758,
    year: 2020,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Pierre',
    surname: 'Gasly',
    nationality: 'French',
    time_x: '1:47.839',
    milliseconds: 107839,
    year: 2020,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Charles',
    surname: 'Leclerc',
    nationality: 'Monegasque',
    time_x: '1:47.840',
    milliseconds: 107840,
    year: 2020,
    name_y: 'Circuit de Spa-Francorchamps',
  },
  {
    forename: 'Pierre',
    surname: 'Gasly',
    nationality: 'French',
    time_x: '1:47.844',
    milliseconds: 107844,
    year: 2020,
    name_y: 'Circuit de Spa-Francorchamps',
  },
];
